### ISSUE TITLE
Training.py generating runtime error

### ISSUE THREAD

**Issue by Ams0x57** [Cly1st/ECG-Arrhythmia-Classification-using-Artificial-Neural-Network#2]
Hi there,

When I run the Training.py I get the following error after the first epoch:
`ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 40799, 128), found shape=(None, 128)`

I would appreciate it if you could direct me to a solution.

**Comment by ughshwin** [comment]
> 

Change input shape from "input_shape=(input_shape)" to "input_shape=(None, 128)" it will fix the code

**Comment by Cly1st** [comment]
Hello @Ams0x57, sorry for the late reply, you can follow @AshwinGupta3012 suggestion.
However, I also updated the codes as well, you can check it out.
